on: [push]

jobs:  
  Uploading-job:  
    name: 'Run Task on Sofy Web'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'Run Task'
        env:
          project_id: '69773c4d1749de90bd7b6bb4'
          subscription_key: F0D2B9BF-930D-486B-B3A4-348AAF8902FE
          prompt: 'open sofy.ai. Go to login page'
        uses: 'SOFYDEVELOPER/Sofy-Web-Task-Action@main'        
